notifications:
    email: false
dist: xenial
language: go
cache:
  directories:
    - $HOME/dep/sassc/bin
go:
  - 1.11.x
before_install:
  - scripts/ci_build_sassc.sh
  - export PATH=$PATH:$HOME/dep/sassc/bin
install: true
branches:
    only:
        - master
env:
    - GO111MODULE=on
script:
    - make build
    - make test
